In [1]:
cmf_rateslib_root = '../../'
import sys
if cmf_rateslib_root not in sys.path:
    sys.path.append(cmf_rateslib_root)
import numpy as np

In [2]:
from cmf_rateslib.curves.base_curve import BaseZeroCurve

In [3]:
curve = BaseZeroCurve(np.array([0,2,5,10]), [0.01, 0.02, 0.03, 0.03],'L-R-1D')
curve1 = BaseZeroCurve(np.array([0,2,5,10]), [0.01, 0.02, 0.03, 0.03],'L-R-1D')
curve2 = BaseZeroCurve(np.array([0,2,5,10]), [0.01, 0.02, 0.03, 0.03],'L-R-1D')

In [4]:
curve._interp_method

['L', 'R', '1D']

In [5]:
from cmf_rateslib.rates.simple_pca import SimplePCAModel
from cmf_rateslib.rates.mean_reverting_pca import MeanRevertingPCAModel

In [6]:
maturities = [0,2,5,10]
loadings = np.array([[1,1,1,1],[0,1,2,3],[2,1,1,2]]).T
vols = [0.01,0.005,0.001]
print(loadings)

[[1 0 2]
 [1 1 1]
 [1 2 1]
 [1 3 2]]


In [7]:
model = SimplePCAModel(maturities,loadings,vols)

In [8]:
curves_num = 6
existing_curves = []
for i in range (1,1+curves_num):
    existing_curves.append(BaseZeroCurve(np.array([0,2,5,10]), [0.01+np.random.normal(0.0,0.001),
                                                                0.03+np.random.normal(0.0,0.001),
                                                                0.04+np.random.normal(0.0,0.001),
                                                                0.07+np.random.normal(0.0,0.001)],'L-R-1D'))

a1,a2 = model.fit(existing_curves,[0,2,5,7,9])


In [9]:
maturities = [0,2,5,10]
loadings = np.array([[1,1,1,1],[0,1,2,3],[2,1,1,2]]).T
vols = [0.01,0.005,0.001]
theta = [0.001,0.002,-0.003]
kappa = 0.01 * np.array([[1,0,0],[0,1,0],[0,0,2]]).T
mean_rev_model = MeanRevertingPCAModel(maturities,loadings,vols,theta,kappa)

In [10]:
mean_rev_model.evolve_zero_curve(curve,5,1/252)

[0.01 0.02 0.03 0.03]
[[1 0 2]
 [1 1 1]
 [1 2 1]
 [1 3 2]]
[ 0.01950006  0.00699999 -0.00500003]
